### ISSUE TITLE
incorrect function call

### ISSUE THREAD

**Issue by ssabelis** [picovico/php-sdk#9]
In Picovico.php on line 114:
$this->get_video (this function does not exist)
I think it should be $this->get

**Comment by acpmasquerade** [comment]
Fixed.

**Comment by acpmasquerade** [comment]
SDK has been updated with more features like duplicate video / see last draft / get last 15 videos, etc. 

Also a built-in command line utility for picovico is available. 

the sdk is now available on composer as well.

https://packagist.org/packages/picovico/php-sdk
